version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    TASK_DEFINITION_NAME: "data-processing-cluster-task"
    CLUSTER_NAME: "data-processing-cluster"
    SERVICE_NAME: "data-processing-service"
    REPOSITORY_URL: "471112833452.dkr.ecr.eu-central-1.amazonaws.com/optimization-backend-prod"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y jq python3-pip
      - pip3 install awscli

  pre_build:
    commands:
      - echo "Authenticating with ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo "Fetching current task definition..."
      - >
        TASK_DEFINITION=$(aws ecs describe-task-definition
        --task-definition $TASK_DEFINITION_NAME
        --region $AWS_DEFAULT_REGION)
      - echo "Creating new task definition..."
      - >
        NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URL:$IMAGE_TAG"
        '.taskDefinition |
        .containerDefinitions[0].image = $IMAGE |
        del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
      - echo "Registering new ECS task definition..."
      - >
        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition
        --region $AWS_DEFAULT_REGION
        --cli-input-json "$NEW_TASK_DEFINITION"
        --query 'taskDefinition.taskDefinitionArn' --output text)
      - |
        if [ -z "$NEW_TASK_DEFINITION_ARN" ]; then
          echo "Error: Failed to register task definition."
          exit 1
        fi

  post_build:
    commands:
      - echo "Updating ECS service with new task definition..."
      - echo "NEW_TASK_DEFINITION_ARN is $NEW_TASK_DEFINITION_ARN" # Debugging step
      - >
        aws ecs update-service
        --region $AWS_DEFAULT_REGION
        --cluster $CLUSTER_NAME
        --service $SERVICE_NAME
        --task-definition $NEW_TASK_DEFINITION_ARN
      - echo "Waiting for ECS service to stabilize..."
      - >
        aws ecs wait services-stable
        --region $AWS_DEFAULT_REGION
        --cluster $CLUSTER_NAME
        --services $SERVICE_NAME
      - echo "Deployment completed successfully."

artifacts:
  files:
    - "**/*"
